import LegalDocument from "@/components/LegalDocument";

const List = ({ items }: { items: string[] }) => <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>;

export default function PrivacyPage() {
  return <LegalDocument title="Privacy Policy" lastUpdated="September 17, 2026" intro={<><p>Curatyn (&quot;Curatyn&quot;, &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) provides a platform designed to help job seekers organize their CVs, analyze job descriptions, prepare tailored application materials, and streamline the job application process.</p><p>This Privacy Policy explains how we collect, use, store, disclose, and protect personal information when you use Curatyn. By using Curatyn, you acknowledge that you have read and understood this Privacy Policy.</p></>} sections={[
    { title: "Who We Are", children: <><p>Curatyn is operated by:</p><p><strong>Legal Name:</strong> Curatyn<br /><strong>Trading Name:</strong> Curatyn<br /><strong>Country:</strong> Nigeria<br /><strong>Email:</strong> deuniq01@gmail.com<br /><strong>Website:</strong> https://curatyn.vercel.app</p></> },
    { title: "Information We Collect", children: <><p>We collect information that you provide directly, information generated through your use of Curatyn, and, where applicable, information received from connected services.</p><h3>Account information</h3><List items={["Name and email address", "Password or authentication credentials", "Account preferences and security information"]} /><h3>CV and career information</h3><p>This may include contact details, employment history, education, skills, certifications, projects, professional summaries, and other information you choose to include in a CV.</p><h3>Job descriptions and applications</h3><p>We may process job titles, company names, requirements, responsibilities, qualifications, locations, recruiter contact details, application status, selected CVs, cover letters, email content, and review information. Screenshots may be processed to extract relevant text.</p><h3>Connected email accounts</h3><p>If you connect Gmail or Outlook, we may receive the account identification and OAuth access or refresh tokens needed to create or send application emails. We do not sell your email account information.</p><h3>Technical information</h3><p>We may collect IP address, browser and device type, operating system, pages accessed, timestamps, error logs, and authentication and security logs.</p></> },
    { title: "How We Use Your Information", children: <><p>We use personal information to create and manage accounts, store CVs, process job descriptions, match CVs to opportunities, generate application materials, create drafts, send emails when explicitly authorized, provide support, secure the Service, prevent fraud, and improve product performance.</p><p>We will not use private CVs, job applications, or email content for unrelated purposes without an appropriate legal basis or your permission.</p></> },
    { title: "AI Processing", children: <><p>Curatyn may use AI-assisted functionality to extract job information, identify requirements, match job descriptions with CVs, and generate cover letters or other application content.</p><p>AI output is a suggestion and may be inaccurate, incomplete, or inappropriate. You remain responsible for reviewing content, confirming accuracy, choosing the CV, confirming recipients, and deciding whether to submit an application.</p></> },
    { title: "Email and Application Sending", children: <p>When you instruct Curatyn to send an application email, relevant information may be transmitted to your connected email provider. Google, Microsoft, and other providers have their own privacy policies and terms, which also apply to their services.</p> },
    { title: "Legal Bases for Processing", children: <p>Depending on the circumstances and applicable law, processing may be based on your consent, the need to provide the Service or perform a contract, legitimate business interests, legal obligations, or another lawful basis. You may withdraw consent where permitted by law.</p> },
    { title: "How We Share Information", children: <><p>We do not sell your personal information. We may share information with trusted providers necessary to operate Curatyn, including:</p><List items={["Application, database, storage, backup, and monitoring providers", "AI providers when AI functionality is requested", "Connected email providers when you request email functionality", "Authentication and security providers", "Authorities where required to comply with law or protect rights", "Successors in a merger, acquisition, financing, or sale of assets"]} /></> },
    { title: "International Data Transfers", children: <p>Service providers may be located outside your country of residence. Where applicable law requires safeguards for international transfers, we will seek to implement appropriate safeguards.</p> },
    { title: "Data Retention", children: <p>We retain personal information only as long as reasonably necessary for the purposes described here, unless a longer period is required by law. CVs may be retained until you delete them or close your account. Security records and backups may remain temporarily.</p> },
    { title: "Your Rights", children: <><p>Depending on your location and applicable law, you may have the right to access, correct, delete, restrict, object to, or request portability of your information, withdraw consent, and lodge a complaint with a data protection authority.</p><p>Contact us to exercise applicable rights. We may need to verify your identity first.</p></> },
    { title: "Account and Data Deletion", children: <p>You may request deletion of your account and associated information by contacting deuniq01@gmail.com. Some information may be retained where required by law or reasonably necessary for security, fraud prevention, dispute resolution, or enforcement.</p> },
    { title: "Cookies and Similar Technologies", children: <p>Curatyn may use cookies to keep you signed in, maintain sessions, remember preferences, provide security, understand usage, and improve performance. Where required, we will request consent before placing non-essential cookies.</p> },
    { title: "Children's Privacy", children: <p>Curatyn is intended for people legally able to use the Service and is not directed toward children. We do not knowingly collect children&apos;s information where prohibited by law.</p> },
    { title: "Security", children: <><p>We use reasonable technical and organizational measures designed to protect personal information, including password hashing, encryption of sensitive credentials and tokens, access controls, secure authentication, database security, monitoring, and backups.</p><p>No internet-based service can guarantee absolute security. Protect your credentials and notify us if your account may be compromised.</p></> },
    { title: "Third-Party Services", children: <p>Curatyn may integrate with email, hosting, AI, authentication, analytics, payment, and infrastructure providers. Their own terms and privacy policies apply to your use of those services.</p> },
    { title: "Changes to This Privacy Policy", children: <p>We may update this Privacy Policy. When material changes are made, we may provide notice through the Service, by email, or by another appropriate method. The date at the top indicates the latest version.</p> },
    { title: "Contact Us", children: <p><strong>Curatyn</strong><br />Email: deuniq01@gmail.com<br />Website: https://curatyn.vercel.app</p> },
    { title: "Governing Privacy Law", children: <p>This Privacy Policy operates alongside applicable data protection and privacy laws and does not limit rights that cannot lawfully be limited.</p> },
  ]} />;
}
