import LegalDocument from "@/components/LegalDocument";

const List = ({ items }: { items: string[] }) => <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>;

export default function TermsPage() {
  return <LegalDocument title="Terms of Service" lastUpdated="September 17, 2026" intro={<><p>Welcome to Curatyn. These Terms of Service (&quot;Terms&quot;) govern your access to and use of the Curatyn website, application, software, and related services (collectively, the &quot;Service&quot;).</p><p>By creating an account or using Curatyn, you agree to these Terms. If you do not agree, you should not use the Service.</p></>} sections={[
    { title: "About Curatyn", children: <><p>Curatyn helps users store CVs, analyze job descriptions, identify requirements, match CVs to opportunities, generate application materials, prepare cover letters and emails, review applications, connect supported email accounts, and streamline parts of the application process.</p><p>Curatyn is a productivity and application-assistance tool. It is not an employer, recruiter, employment agency, immigration service, legal adviser, or career-placement agency.</p></> },
    { title: "Eligibility", children: <p>You must be legally capable of entering a binding agreement in your jurisdiction. You represent that you meet the applicable age requirement, can enter these Terms, provide accurate information, use the Service lawfully, and comply with these Terms.</p> },
    { title: "Your Account", children: <><p>You are responsible for accurate account information, credential confidentiality, account security, and activity through your account subject to applicable law. Do not share credentials or allow unauthorized access. We may restrict accounts involved in abuse, fraud, security threats, or violations.</p></> },
    { title: "Your Content", children: <><p>You retain ownership of CVs, job descriptions, application information, documents, images, and other materials you provide. You grant Curatyn a limited, non-exclusive, worldwide license to host, store, reproduce, process, transmit, and use that content only as reasonably necessary to provide, secure, maintain, and improve the Service, subject to the Privacy Policy and applicable law.</p><p>The license ends when relevant content is deleted, except where retention is reasonably necessary for legal, security, backup, dispute-resolution, or other legitimate purposes.</p></> },
    { title: "You Must Have the Right to Upload Content", children: <><p>You may upload only information and documents that you have the legal right to use. Do not upload stolen documents, unlawfully obtained information, unauthorized confidential information, another person&apos;s personal information without a lawful reason, malware, or infringing content.</p></> },
    { title: "AI-Generated Content", children: <><p>Curatyn may use AI to summarize jobs, extract company or role details, match CVs, generate cover letters, create subject lines, and prepare other application content.</p><p>AI output may contain errors, omissions, misinterpretations, formatting problems, or inappropriate recommendations. You must review it and ensure your final application accurately represents your experience, qualifications, education, employment history, and other personal information.</p></> },
    { title: "No Guarantee of Employment", children: <><p>Curatyn does not guarantee employment, interviews, recruiter responses, job offers, acceptance, improved success, faster hiring, accurate matches, or any particular career outcome.</p><p>The decision to apply and the content submitted to an employer remain your responsibility.</p></> },
    { title: "CV Matching", children: <p>CV matching is automated assistance and may make mistakes. You are responsible for reviewing the selected CV. Curatyn does not guarantee that a recommendation is the most appropriate CV for a position.</p> },
    { title: "Email Functionality", children: <><p>Curatyn may create drafts or send application emails through supported providers. You authorize the email action you explicitly request.</p><p>Before sending, verify the recipient, company, job title, CV, cover letter, subject, body, and other application information. Third-party providers may impose their own limits, policies, and security requirements.</p></> },
    { title: "Third-Party Services", children: <p>Curatyn may integrate with Google, Microsoft, AI providers, cloud infrastructure, storage, authentication, payment, and other providers. Your use of those services may be subject to their terms and policies. Curatyn does not control their availability, policies, security, or performance except where required by law.</p> },
    { title: "Acceptable Use", children: <><p>You agree not to use Curatyn to:</p><List items={["Break the law, commit fraud, or impersonate another person", "Intentionally misrepresent qualifications or submit fraudulent applications", "Harass, threaten, or violate another person's privacy", "Distribute malware or malicious files", "Gain unauthorized access or circumvent security controls", "Interfere with the Service, abuse APIs, scrape data, or reverse engineer where prohibited", "Infringe intellectual-property rights", "Send spam or unauthorized bulk email, phishing, or other abusive content"]} /><p>We may investigate suspected violations and take appropriate action.</p></> },
    { title: "Intellectual Property", children: <><p>Curatyn and its software, design, branding, interfaces, graphics, documentation, and original materials are owned by or licensed to Curatyn unless stated otherwise.</p><p>Except as permitted by these Terms or applicable law, you may not copy the software, reproduce branding, resell the Service, modify or distribute software, create derivative works, or reverse engineer where prohibited. Your content remains yours.</p></> },
    { title: "Feedback", children: <p>If you provide suggestions, ideas, recommendations, bug reports, or other feedback, you grant us permission to use it without restriction or compensation, provided that doing so does not disclose private personal information contrary to the Privacy Policy.</p> },
    { title: "Service Availability", children: <p>We make reasonable efforts to keep Curatyn available, but do not guarantee uninterrupted, error-free, completely secure, universally compatible, or fully retained Service. Maintenance, upgrades, infrastructure failures, security incidents, third-party outages, or circumstances outside our control may cause interruptions.</p> },
    { title: "Changes to the Service", children: <p>We may modify, suspend, replace, or discontinue features as the product develops. Where required by law, we will provide appropriate notice of material changes.</p> },
    { title: "Paid Services", children: <p>If Curatyn introduces paid plans or features, pricing, taxes, payment processing, subscription terms, cancellation rules, and refunds will be disclosed before purchase. Additional terms may apply.</p> },
    { title: "Termination", children: <p>You may stop using Curatyn at any time. We may suspend or terminate access for material violations, unlawful use, security risks, threats to the Service, legal requirements, or discontinuation. Where appropriate and legally permitted, we may provide notice.</p> },
    { title: "Data After Termination", children: <p>After termination or deletion, we may delete information according to the Privacy Policy and retention requirements. Information may remain temporarily in backups, security records, or where legally required.</p> },
    { title: "Disclaimers", children: <p>To the maximum extent permitted by law, Curatyn is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We do not guarantee that the Service, AI output, extraction, matching, email delivery, integrations, or employment outcomes will be accurate, uninterrupted, error-free, or suitable for every user. Nothing excludes a protection that cannot lawfully be excluded.</p> },
    { title: "Limitation of Liability", children: <p>To the maximum extent permitted by law, Curatyn and its owners, employees, contractors, affiliates, and providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, including loss of employment opportunity, revenue, profits, data, business opportunities, reputation, or intangible losses. Nothing limits liability that cannot legally be limited.</p> },
    { title: "Indemnification", children: <p>To the extent permitted by law, you agree to defend, indemnify, and hold harmless Curatyn and its owners, employees, contractors, affiliates, and providers from claims, damages, liabilities, costs, and expenses arising from your violation of these Terms, unlawful use, uploaded content, infringement, misuse of third-party services, or violation of law.</p> },
    { title: "Privacy", children: <p>Your use of Curatyn is also governed by our <a href="/privacy">Privacy Policy</a>, which explains how we collect, use, store, and protect personal information.</p> },
    { title: "Governing Law", children: <p>These Terms shall be governed by the laws of <strong>Nigeria</strong>, without regard to conflict-of-law principles, except where mandatory law provides otherwise.</p> },
    { title: "Dispute Resolution", children: <p>Before formal proceedings, you agree to contact Curatyn and attempt in good faith to resolve a dispute. Contact: <strong>deuniq01@gmail.com</strong>. This does not prevent rights or remedies that cannot legally be waived.</p> },
    { title: "Changes to These Terms", children: <p>We may update these Terms. For material changes, we may provide notice through the Service, by email, or another appropriate method. Continued use after the effective date constitutes acceptance to the extent permitted by law.</p> },
    { title: "Severability", children: <p>If a provision is invalid, unlawful, or unenforceable, the remaining provisions continue to apply to the extent permitted by law.</p> },
    { title: "Entire Agreement", children: <p>These Terms, the Privacy Policy, and additional terms incorporated into the Service constitute the agreement between you and Curatyn regarding the Service, unless a separate written agreement applies.</p> },
    { title: "Contact", children: <p><strong>Curatyn</strong><br />Email: deuniq01@gmail.com<br />Website: https://curatyn.vercel.app</p> },
  ]} />;
}
